import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import SessionProvider from "~/components/SessionProvider";
import Header from "~/components/Header";
import { getServerAuthSession } from "~/server/auth";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex h-svh flex-col">
        <SessionProvider session={session}>
          <Header />
          <main
            className="bg-blohsh-beige flex-1
          "
          >
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
